export const metadata = { title: 'Methods & credits', description: 'How Sol Loom represents orbital data, scale, and time.' };
export default function AboutPage() {
  return <main className="about-page">
    <header className="about-header"><a className="brand" href="/"><span className="brand-mark"/> SOL LOOM</a><a href="/">← RETURN TO THE MODEL</a></header>
    <article className="about-content"><p className="eyebrow">METHODS & CREDITS</p><h1>Space is extraordinary.<br/><em>The details matter.</em></h1><p className="about-lede">Sol Loom brings our solar neighborhood within reach. Its orbits are calculated from a date; its visual scale is deliberately adjusted so you can find a world, move closer, and see it in motion.</p>
    <section><span>01</span><div><h2>Where are the planets?</h2><p>The eight planets use JPL’s published approximate Keplerian elements and their rates from Table 1, evaluated for the selected date. Newton iteration solves Kepler’s equation; orbital inclination and orientation place the resulting ellipse in the J2000 ecliptic frame. Earth uses the Earth–Moon barycenter approximation.</p><p className="callout">Dates are limited to 1 January 1900–1 January 2050. UTC is used as an approximation to the ephemeris timescale. This is an educational model, not a precision ephemeris for navigation or eclipse prediction.</p><p>The Moon and Pluto use simplified illustrative Keplerian orbits, with approximate phases. Rotation periods and axial tilts are represented; surface orientation and cloud patterns are illustrative. Positions are calculated locally with JavaScript double precision.</p></div></section>
    <section><span>02</span><div><h2>Two ways to see distance</h2><p><strong>Explore</strong> compresses orbital spacing and enlarges bodies, so the inner and outer solar system can share a readable view. <strong>True distance ratios</strong> renders planetary orbital distances at two scene units per astronomical unit. Planetary radii and the Moon’s orbit remain enlarged in both modes. Neither mode represents simultaneous true size and distance.</p><p>Planet view shows the selected body and its immediate family. System view brings the wider context back. The scale disclosure stays visible at the bottom of the screen.</p></div></section>
    <section><span>03</span><div><h2>Make the view yours</h2><p>Drag to orbit, scroll or pinch to zoom, and choose a world from the lower strip. Press <kbd>/</kbd> to search, <kbd>Space</kbd> to pause or play, and <kbd>Home</kbd> to return to the solar system. The date opens a UTC date picker. Reverse time with the curved arrow; set its rate with the speed menu.</p><p>Share this view saves the selected body, date, speed, layers, scale, and exact camera pose into the URL. The help menu contains a keyboard-accessible catalog. Reduced-motion preferences remove camera-flight animation. Rendering quality caps pixel density to limit GPU load.</p></div></section>
    <section><span>04</span><div><h2>Real maps. Clear credits.</h2><p>Planet and Moon textures are by Solar System Scope / INOVE, licensed under Creative Commons Attribution 4.0. They are based on NASA imagery, with enhanced colors and reconstructed areas where coverage is incomplete. Earth’s clouds are a fixed illustrative map. The Sun uses a stylized procedural material; Pluto uses a plain illustrative surface.</p><div className="source-links"><a href="https://www.solarsystemscope.com/textures/">Solar System Scope textures ↗</a><a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0 ↗</a><a href="https://ssd.jpl.nasa.gov/planets/approx_pos.html">JPL orbital elements ↗</a><a href="https://science.nasa.gov/solar-system/">NASA solar system ↗</a></div></div></section>
    </article><footer className="about-footer"><span>THE SOLAR SYSTEM, ALIVE IN YOUR BROWSER.</span><span>SOL LOOM / SECOND EDITION</span></footer>
  </main>;
}
