'use client';
import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import SolarScene, { texturePath } from './SolarScene';
import { bodies, bodyBySlug, formatPeriod } from '@/lib/bodies';
import { clampTime, MIN_TIME, MAX_TIME } from '@/lib/ephemeris';
import { readState, stateUrl, type ViewState } from '@/lib/view-state';

const speeds=[.000011574, .041667,1,10,100];
const speedText=(v:number)=>Math.abs(v)<.001?'Real time':Math.abs(v)<.1?'1 hour / sec':Math.abs(v)===1?'1 day / sec':Math.abs(v)+' days / sec';
const chapters=[{body:'earth',title:'Our pale blue home',text:'Oceans cover most of Earth. Its thin atmosphere and liquid water make this a world unlike any other.'},{body:'moon',title:'Our nearest neighbor',text:'The Moon keeps the same face toward Earth. Switch to the system view to see their orbital relationship.'},{body:'mars',title:'A world of possibilities',text:'Look past the rust-red surface: Mars carries evidence of rivers, lakes, and a wetter past.'},{body:'jupiter',title:'The giant of the family',text:'Jupiter contains more mass than all the other planets combined. Its banded atmosphere never stands still.'},{body:'saturn',title:'A million icy worlds',text:'Saturn’s rings are not solid. They are countless fragments of ice and rock sharing an orbital plane.'},{body:'neptune',title:'At the edge of the planets',text:'Sunlight takes over four hours to reach Neptune. One orbit lasts almost 165 Earth years.'}];
function Thumb({slug}:{slug:string}) {const b=bodyBySlug(slug)!;const src=texturePath(slug);return <span className={'thumb thumb-'+slug} style={{'--planet':b.color,backgroundImage:src?'url('+src+')':undefined} as CSSProperties}/>;}
export default function SolarExperience({initialSlug,embedded=false}:{initialSlug?:string;embedded?:boolean}){
  const [state,setState]=useState<ViewState>(()=>readState(typeof window==='undefined'?'':window.location.search,initialSlug));
  const [query,setQuery]=useState(''),[panel,setPanel]=useState<'none'|'search'|'settings'|'help'|'date'|'catalog'>('none');
  const [notice,setNotice]=useState(''),[error,setError]=useState(false),[details,setDetails]=useState(false),[reset,setReset]=useState(0),[tour,setTour]=useState(-1);
  const [dateInput,setDateInput]=useState(''),[dateError,setDateError]=useState('');
  const time=useRef(state.time),cameraState=useRef<number[]|undefined>(state.camera),searchRef=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null);
  const current=useRef(state);current.current=state; const restore=useRef(false);
  const [reduced,setReduced]=useState(false);
  useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
  const change=useCallback((patch:Partial<ViewState>)=>setState(s=>({...s,...patch,camera:undefined})),[]);
  const select=useCallback((body:string)=>{change({body,view:'focus'});setPanel('none');setDetails(false);setReset(r=>r+1);},[change]);
  useEffect(()=>{
    let frame:number,previous=performance.now(),last=previous;
    const tick=(now:number)=>{const dt=Math.min((now-previous)/1000,.1);previous=now;
      if(!document.hidden){const next=time.current+current.current.speed*dt*86400000;time.current=clampTime(next);if(next!==time.current&&current.current.speed!==0){change({speed:0});setNotice('Reached the supported date range.');}}
      if(now-last>200){setState(s=>s.time===time.current?s:({...s,time:time.current}));last=now;}
      frame=requestAnimationFrame(tick);
    };frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
  },[change]);
  useEffect(()=>{const timer=setTimeout(()=>{if(restore.current){restore.current=false;return;}history.replaceState(null,'',stateUrl({...state,time:time.current,camera:cameraState.current},embedded));},250);return()=>clearTimeout(timer);},[state.body,state.view,state.scale,state.speed,state.labels,state.orbits,embedded]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{const back=()=>{const s=readState(location.search,location.pathname.split('/body/')[1]);time.current=s.time;restore.current=true;setState(s);setReset(r=>r+1);};window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);},[]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>{if(panel!=='none'){dialog.current?.showModal();if(panel==='search')searchRef.current?.focus();}else dialog.current?.close();},[panel]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;
    if(e.key==='/'){e.preventDefault();setPanel('search');}
    if(e.code==='Space'){e.preventDefault();change({speed:current.current.speed?0:1});}
    if(e.key==='Escape'){setPanel('none');if(!dialog.current?.open)change({view:'system'});}
    if(e.key==='Home'){e.preventDefault();change({view:'system'});}
  };window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[change]);
  const body=bodyBySlug(state.body)!;
  const overview=state.view!=='focus';
  const setTime=(timestamp:number)=>{time.current=clampTime(timestamp);change({time:time.current});};
  const share=async()=>{const url=new URL(stateUrl({...current.current,time:time.current,camera:cameraState.current},embedded),location.origin).href;history.replaceState(null,'',url);try{await navigator.clipboard.writeText(url);setNotice('Link copied — this view, date, and camera are saved.');}catch{setNotice('Copy the address bar to share this exact view.');}};
  const goTour=(index:number)=>{setTour(index);change({speed:0});select(chapters[index].body);};
  const result=bodies.filter(b=>(b.name+' '+b.kind).toLowerCase().includes(query.toLowerCase()));
  return <main className={'observatory '+(embedded?'is-embedded':'')}>
    <button className="skip-link" onClick={()=>setPanel('catalog')}>Explore the accessible catalog</button>
    <div className="universe" role="region" aria-label="Interactive solar system. Drag to orbit, scroll or pinch to zoom."><SolarScene state={state} time={time} onSelect={select} cameraState={cameraState} reduced={reduced} reset={reset} onError={()=>setError(true)}/></div>
    <header className="masthead">
      <button className="wordmark" onClick={()=>{change({view:'system'});setTour(-1);setReset(r=>r+1);}} aria-label="Sol Loom system overview"><span className="solar-mark">◉</span><span>SOL<span className="wordmark-light"> LOOM</span><small>THE SOLAR SYSTEM, ALIVE.</small></span></button>
      <nav className="view-tabs" aria-label="View"><button className={overview?'active':''} onClick={()=>change({view:'system'})}>Solar system</button><button className={!overview?'active':''} onClick={()=>select(state.body)}>Planet view</button></nav>
      <div className="header-tools"><button className="search-button" aria-label="Find a world" onClick={()=>{setQuery('');setPanel('search');}}><span>⌕</span><span className="desktop-label">Find a world</span><kbd>/</kbd></button><button className="square" aria-label="Share current view" onClick={share}>↗</button><button className="square" aria-label="Display settings" onClick={()=>setPanel('settings')}>☷</button><button className="square" aria-label="Help and controls" onClick={()=>setPanel('help')}>?</button></div>
    </header>
    <section className="context-title"><p className="eyebrow">{overview?'YOUR COSMIC NEIGHBORHOOD':body.kind==='moon'?'EARTH’S NATURAL SATELLITE':body.kind.toUpperCase()+(body.kind==='planet'?' / '+String(bodies.filter(b=>b.kind==='planet').findIndex(b=>b.slug===body.slug)+1).padStart(2,'0'):'')}</p><h1>{overview?'A little perspective.':body.name}<span>{overview?'One star. Eight planets. Endless discovery.':body.fact}</span></h1></section>
    <div className="orientation"><span>J2000 ECLIPTIC</span><button aria-pressed={state.view==='top'} onClick={()=>{change({view:state.view==='top'?'system':'top'});setReset(r=>r+1);}} title="Toggle top-down view">⊕<small>{state.view==='top'?'Angled view':'Top view'}</small></button></div>
    {overview?<aside className="discovery-card"><span className="eyebrow">START SOMEWHERE FAMILIAR</span><div className="discovery-row"><Thumb slug="earth"/><div><h2>Home, from a distance.</h2><p>Meet Earth. Then see what lies beyond.</p></div></div><button className="accent-button" onClick={()=>select('earth')}>Explore Earth <span>↗</span></button><button className="text-button" onClick={()=>goTour(0)}>Take a short journey <span>→</span></button></aside>:<aside className="body-card">
      <div className="card-heading"><span className="eyebrow">FIELD NOTES</span><button className="quiet" onClick={()=>change({view:'system'})} aria-label="Return to solar system">↗</button></div><p className="body-description">{body.description}</p>
      <dl className="metrics"><div><dt>Radius</dt><dd>{body.radiusKm.toLocaleString()} <small>km</small></dd></div><div><dt>One year</dt><dd>{body.periodDays?formatPeriod(body.periodDays).replace('Earth ',''):'—'}</dd></div><div><dt>One rotation</dt><dd>{(Math.abs(body.rotationHours)/24).toFixed(2)} <small>days</small></dd></div><div><dt>Axial tilt</dt><dd>{body.axialTilt}°</dd></div></dl>
      <button className="details-toggle" onClick={()=>setDetails(v=>!v)} aria-expanded={details}>Orbital details <span>{details?'−':'+'}</span></button>{details&&<div className="orbital-details"><p>Mean distance <strong>{body.distanceMkm.toLocaleString()} million km</strong></p><p>Eccentricity <strong>{body.eccentricity}</strong></p><p>Inclination <strong>{body.inclination}°</strong></p><small>{body.parent?'Relative to Earth. Simplified lunar orbit.':body.slug==='pluto'?'Illustrative dwarf-planet orbit.':'Heliocentric; JPL approximate elements.'} Surface maps are illustrative.</small></div>}
      {body.slug==='earth'&&<button className="moon-link" onClick={()=>select('moon')}>☾ Visit the Moon <span>→</span></button>}
      <button className="share-view" onClick={share}>↗ Share this view</button>
    </aside>}
    {tour>=0&&<section className="journey"><div><span className="eyebrow">A SHORT JOURNEY / {tour+1} OF {chapters.length}</span><button className="quiet" aria-label="Close journey" onClick={()=>setTour(-1)}>×</button></div><h2>{chapters[tour].title}</h2><p>{chapters[tour].text}</p><footer><button disabled={tour===0} onClick={()=>goTour(tour-1)}>← Previous</button><button onClick={()=>tour===chapters.length-1?setTour(-1):goTour(tour+1)}>{tour===chapters.length-1?'Finish':'Next world'} →</button></footer></section>}
    {error&&<section className="graphics-error"><h2>Explore without 3D</h2><p>Your browser couldn’t start the 3D view. Every world is available in the catalog.</p><button onClick={()=>setPanel('catalog')}>Open catalog</button><button onClick={()=>location.reload()}>Try again</button></section>}
    <div className="bottom-console">
      <div className="explorer-caption"><span>{overview?'EXPLORE THE SOLAR SYSTEM':'CONTINUE EXPLORING'}</span><span>Drag to orbit <b>·</b> Scroll to zoom</span></div>
      <nav className="planet-strip" aria-label="Choose a celestial body">{bodies.filter(b=>b.kind!=='moon').map(b=><button key={b.slug} className={state.body===b.slug&&!overview?'active':''} onClick={()=>{select(b.slug);setTour(-1);}}><Thumb slug={b.slug}/><span>{b.name}</span>{state.body===b.slug&&!overview&&<i/>}</button>)}</nav>
      <section className="time-bar" aria-label="Simulation time controls">
        <div className="time-buttons"><button className={state.speed<0?'active':''} aria-label="Reverse time" aria-pressed={state.speed<0} onClick={()=>change({speed:-Math.abs(state.speed||1)})}>↶</button><button className="play" aria-label={state.speed?'Pause time':'Play time'} onClick={()=>change({speed:state.speed?0:1})}>{state.speed?'Ⅱ':'▶'}</button></div>
        <button className="date-readout" aria-label="Choose simulation date" onClick={()=>{setDateInput(new Date(time.current).toISOString().slice(0,16));setDateError('');setPanel('date');}}><span>{new Date(state.time).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'})}</span><small>{new Date(state.time).toISOString().slice(11,16)} UTC <span>⌄</span></small></button>
        <div className="timeline" aria-hidden="true">{Array.from({length:29},(_,i)=><i key={i} className={i===14?'center':''}/>)}<span>{state.speed===0?'TIME PAUSED':state.speed<0?'TRAVELING BACKWARD':'TIME IN MOTION'}</span></div>
        <label className="speed-control"><span>Speed</span><select aria-label="Time speed" value={Math.abs(state.speed)||1} onChange={e=>change({speed:Number(e.target.value)*(state.speed<0?-1:1)})}>{speeds.map(s=><option value={s} key={s}>{speedText(s)}</option>)}{!speeds.includes(Math.abs(state.speed))&&state.speed!==0&&<option value={Math.abs(state.speed)}>{speedText(state.speed)}</option>}</select></label>
        <button className="now" onClick={()=>{setTime(Date.now());change({speed:1});}}>Now ↗</button>
      </section>
      <footer className="status-bar"><button onClick={()=>setPanel('settings')}>{state.scale==='explore'?'Explore scale':'True distance ratios'} <span>· Bodies enlarged{state.scale==='explore'?' · Distances compressed':''}</span></button><a href="/about">Approximate positions <span>· Methods & credits ↗</span></a></footer>
    </div>
    {notice&&<div className="toast" role="status">{notice}</div>}
    <dialog aria-labelledby="control-dialog-title" ref={dialog} className={'control-dialog '+(panel==='catalog'?'catalog-dialog':'')} onCancel={()=>setPanel('none')} onClick={e=>{if(e.target===e.currentTarget)setPanel('none');}}><div className="dialog-heading"><h2 id="control-dialog-title">{panel==='search'?'Find your next world':panel==='settings'?'Make space your own':panel==='date'?'Travel through time':panel==='catalog'?'The solar system':'A few ways to explore'}</h2><button onClick={()=>setPanel('none')} aria-label="Close dialog">×</button></div>
      {panel==='search'&&<><input ref={searchRef} className="search-input" aria-label="Search celestial bodies" placeholder="Try Earth, Saturn, or Moon…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&result[0]){e.preventDefault();e.stopPropagation();select(result[0].slug);}}}/><div className="search-results">{result.map(b=><button key={b.slug} onClick={()=>select(b.slug)}><Thumb slug={b.slug}/><span>{b.name}<small>{b.kind}</small></span><span>↗</span></button>)}{!result.length&&<p>No worlds match “{query}”. Try a planet name.</p>}</div></>}
      {panel==='settings'&&<><p>Shape the view, keep your bearings.</p><label className="setting"><span>Orbital paths<small>See how worlds move around the Sun.</small></span><input type="checkbox" checked={state.orbits} onChange={e=>change({orbits:e.target.checked})}/></label><label className="setting"><span>Body labels<small>Keep each world identifiable.</small></span><input type="checkbox" checked={state.labels} onChange={e=>change({labels:e.target.checked})}/></label><label className="setting"><span>Distance scale</span><select value={state.scale} onChange={e=>change({scale:e.target.value as ViewState['scale']})}><option value="explore">Explore</option><option value="distance">True distance ratios</option></select></label><p className="disclosure">Explore compresses orbital spacing. True distance ratios preserves planetary orbital distances at 2 scene units per AU. Bodies and the Moon’s orbit remain enlarged in both modes.</p><button className="accent-button" onClick={()=>{setReset(r=>r+1);setPanel('none');}}>Reset camera ↗</button></>}
      {panel==='date'&&<form onSubmit={e=>{e.preventDefault();const t=Date.parse(dateInput+'Z');if(!Number.isFinite(t)||t<MIN_TIME||t>MAX_TIME){setDateError('Choose a date from 1900 through 1 January 2050.');return;}setTime(t);change({speed:0});setPanel('none');history.replaceState(null,'',stateUrl({...state,time:t,speed:0},embedded));}}><p>Choose a moment between 1900 and 2050. Dates use UTC.</p><label className="date-field">Date and time<input required type="datetime-local" value={dateInput} min="1900-01-01T00:00" max="2050-01-01T00:00" onChange={e=>setDateInput(e.target.value)}/></label>{dateError&&<p role="alert">{dateError}</p>}<button className="accent-button" type="submit">Go to this moment →</button></form>}
      {panel==='help'&&<><p>Click a planet or choose one below to fly closer.</p><dl className="help-keys"><div><dt>Drag / one finger</dt><dd>Orbit the camera</dd></div><div><dt>Scroll / pinch</dt><dd>Zoom in and out</dd></div><div><dt><kbd>Space</kbd></dt><dd>Pause or play time</dd></div><div><dt><kbd>/</kbd></dt><dd>Find a world</dd></div><div><dt><kbd>Home</kbd></dt><dd>System overview</dd></div></dl><button className="accent-button" onClick={()=>{setPanel('none');goTour(0);}}>Take a short journey →</button><button className="text-button" onClick={()=>setPanel('catalog')}>Browse accessible catalog</button><a className="text-button" href="/about">Read methods & credits ↗</a></>}
      {panel==='catalog'&&<div id="catalog" className="catalog">{bodies.map(b=><article key={b.slug}><h3>{b.name} <small>{b.kind}</small></h3><p>{b.description}</p><p>Radius: {b.radiusKm.toLocaleString()} km · Orbit: {formatPeriod(b.periodDays)}</p><button onClick={()=>select(b.slug)}>Focus {b.name} ↗</button></article>)}</div>}
    </dialog>
  </main>;
}
